cloud-barista/cb-coffeehouse

.github/workflows/contribute-list.yaml, README.md
- Add contribute list action
- Add contributor list section on README.md
=> Add a workflow for contribute-list

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
- Example: Deploying PHP Guestbook application with Redis
- Example: Deploying Weave Scope
=> Describe deploying pods as an example

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
- Add figures 
- Update its description
=> Update of the K8s tutorial

docs/Creating-and-accessing-an-instance-on-MS-Azure-Platform.md
- Apply `<p>` and `<img>` tag to resize figures
- Remove indents
- Make title for sub-sections
=> Update the guide to creating a VM in MS Azure

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
=> Fix typo of kubernetes deploy tutorial

docs/Creating-and-accessing-an-instance-on-GCP.md
저는 웨일 브라우저를 사용하는데 GCP 페이지가 계속 안되서 시간을 많이 잡아 먹었었습니다. 그래서 주의할 점으로 추가하고 싶습니다!
=> Add caution to create a GCP instance

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
- Specify the version of CB-Spider, CB-Tumblebug, cb-network controller
- Add a figure to illustrate Pod-to-Pod communication in detail
- Add thank you note
=> Update the K8s deployment tutorial on Multi-clouds

docs/A-guide-to-the-development-environment-setup-for-Cloud-Barista.md
- Newly create this guide for window users
=> Create a guide to a dev env setup for Cloud-Barista

docs/Creating and accessing an instance on AlibabaCloud.md
Inner link를 달아줬습니다.
이미지를 <p> 태그로 통일 시켜주었습니다.
마지막으로 Ms Azure의 가이드 문서 틀과 Alibaba Cloud의 가이드 문서 틀을 동일하게 맞춰주는 작업을 했습니다.
=> Match the format with other cloud

docs/Creating and accessing an instance on AlibabaCloud.md
#43 
https://github.com/cloud-barista/cb-coffeehouse/issues/43#issuecomment-904257762 참고하여 수정했습니다.
=> Fix format on Alibaba Cloud guide 

docs/Creating-and-accessing-an-instance-on-GCP.md
사용자가 쉽게 문서의 내용을 찾을 수 있도록 Table of conentes를 생성해 Inner link를 달아줬습니다.
다른 Cloud와 통일성을 주기 위해 이미지를 <p>태그를 통해서 표현했습니다. (간혹 ![]()로 표현된 이미지는 오류발생)
VM을 생성, 접근하기 위한 설명을 조금 더 간결하게 표현을 했습니다.
GCP CLI를 통한 가상머신 생성을 하는 방법을 작성했습니다.
=> Matched the format with other clouds and Delete unnecessary content

docs/Creating New AWS Account and setting new VPC and VM.md
1. Fix Invalid URL
2. Add AWS account closed issue
=> Fix Invalid URL (aws doc)

README.en.md, README.md
- Translated the Readme (Korean) into English.
-  #64 
- Please see for any typo in the translations. 
Thanks
=> Added the README in English language

README.en.md, README.md
- Update the guide section for description/information sharing
- Change the link of "Message for future contributors
- Relocate "Read this in other languages" to the top of READMEs
=> Update README.md and README.en.md

docs/vmmem process optimization method.md
When working in Windows, the vmmem process overused memory, resulting in heat and slow down.
There is a way to force this adjustment, and share it.
=> Create vmmem process optimization method.md

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
- Apply CB-Spider v0.4.9 and CB-Tumblebug v0.4.6 CB-Larva v0.0.5
- Improve overall texts
=> Update K8s tutorial

docs/A-step-by-step-tutorial-to-deploy-a-single-Kubernetes-cluster-on-Multi-cloud.md
- Reflect each framework's current information
- Add figures for better understanding
- Enhance description
=> Update the tutorial for K8s cluster across Multi-clouds

docs/Distributed-logging-by-ELK-Stack.md
- Add a PC spec (성능 및 과금 이슈로 ELK 서버를 대체함)
- Add some description for troubleshooting for Elasticsearch, Logstash, Kibana, and Filebeat
- Add Kibana interface images
- Include other minor updates
=> Update distributed logging

scripts/golang/README.md, scripts/golang/go-installation.sh
- Upgrade to go 1.19
- Update README
=> Update the go installation script

scripts/elastic-stack/setup-filebeat.sh
- Support both Debian-like and RedHat-like OSs
=> Add a script to setup Filebeat

scripts/elastic-stack/setup-filebeat.sh
- Add silent or quiet mode option
- Display Filebeat.service status at the end of the script
=> Install Filebeat-related packges with silent mode

docs/Distributed-logging-by-Elastic-Stack.md, docs/Transforming-logs-by-Logstash.md
- Rename from ELK Stack to Elastic Stack
- Add Transforming-logs-by-Logstash.md
=> Update Elastic Stack

docs/Transforming-logs-by-Logstash.md
I tried to improve the description of this article.
Please feel free to adjust.
By the way, thanks to @yunkon-kim for this nice article!
=> Enhance description for Transforming-logs

docs/VSCode/customize-vscode-copilot/write-context-review-code-taking-copilot-to-the-next-level.md
* Add experience developing and using `sync-tb`
=> Update an article, write context review code
